MAX_WIDTH = 800       # Max screen width
MAX_HEIGHT = 800      # Max screen height
STEP = 20             # Units the paddle moves on key press
STEP_BALL = 5         # Units the ball moves per cycle
Y_PADDLE = 300        # Vertical position of the paddle
OFFSET_BOARD = 50     # Margins between screen and play area
TIMER_SLEEP = 0.01    # Control the speed of the game
COLORS_BRICK = ['green', 'blue', 'orange', 'red']   # Possible colors of the brick
ROW_BRICKS = 5        # Number of bricks in a Row
TOTAL_ROWS = 8        # Number of rows of bricks
WIDTH_BRICK = 10      # Width of the brick
